- name: configuring mysql server
  hosts: mysql
  become: yes
  vars:
    mysql_username: root
    mysql_password: ExpenseApp@1
  tasks:
  - name: install mysql libraries
    ansible.builtin.pip:
      name: "{{item}}"
      state: present
      executable: pip3.9
    loop:
    - PyMySQL
    - cryptography
  - name: installing mysql
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: starting mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql
    community.mysql.mysql_info:
      login_user: "{{mysql_username}}"
      login_password: "{{mysql_passowrd}}"
      login_host: mysql.santhoshdatti.online
    register: mysql_info
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "{{mysql_info}}"

  - name: set up the password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_password}}"
    when: mysql_info.failed is true