- name: configuring mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: installing mysql
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: starting mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.santhoshdatti.online
    register: mysql_info
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "{{mysql_info}}"